import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import styles2 from "../styles/header.module.css";
import Navbar from "../components/navbar";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });
const { heroContent, heroWrapper, imageWrapper } = styles2;
const background = require("../public/ruled.png");

export default function Home() {
  return (
    <>
      <Head>
        <title>Double Digits</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main>
        <div className={styles.cover}>
          <img
            className={styles.cover}
            src="/headers.png"
            alt="homepage cover image"
            width={1110}
            height={445}
          />
        </div>

        <div className={styles.latest}>
          <img src="/latest.png" alt="latest stories" width={350} />
        </div>

        <div className={styles.row}>
          <div className={styles.column}>
            <img
              src="/dancing.png"
              alt="kids dancing"
              width={711}
              height={367}
            />
          </div>
          <div className={styles.column}>
            <h1 className={styles.fourthFont}>
              <Link href="/posts/dancing">Dancing Across America</Link>
            </h1>
            <p className={styles.thirdFont}>
              Kids all over the country are dancing at the prom. We heard their
              stories. Who will you take?
            </p>
          </div>
        </div>

        <div className={styles.rowRight}>
          <div className={styles.columnRight}>
            <img
              src="/euphoria.png"
              alt="Euphoria screenshot"
              width={627}
              height={447}
            />
          </div>
          <div className={styles.columnRightText}>
            <h1 className={styles.secondFont}>Season Finale Euphoria</h1>
            <p className={styles.firstFont}>
              We watched the season finale of Euphoria so you don't have to.
              Here's everything we learned that you need to know.
            </p>
          </div>
        </div>
        <br />
      </main>
    </>
  );
}
