import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import styles2 from "../styles/header.module.css";
import Navbar from "../components/navbar";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });
const { heroContent, heroWrapper, imageWrapper } = styles2;
const background = require("../public/ruled.png");

export default function Home() {
  return (
    <>
      <Head>
        <title>Double Digits</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main>
        <div className={styles.cover}>
          <img
            className={styles.cover}
            src="/headers.png"
            alt="cover image"
            width={1156}
            height={464}
          />
        </div>

        <div className={styles.latest}>
          <img src="/latest.png" alt="latest stories" width={350} />
        </div>

        <div className={styles.row}>
          <div className={styles.column}>
            <img
              src="/dancing.png"
              alt="kids dancing"
              width={711}
              height={367}
            />
          </div>
          <div className={styles.column}>
            <h1 className={styles.fourthFont}>
              <Link href="/posts/dancing">Dancing Across America</Link>
            </h1>
            <p className={styles.thirdFont}>
              Kids all over the country are dancing at the prom. We heard their
              stories. Who will you take?
            </p>
          </div>
        </div>

        <div className={styles.rowRight}>
          <div className={styles.columnRight}>
            <img
              src="/euphoria.png"
              alt="Euphoria screenshot"
              width={627}
              height={447}
            />
          </div>
          <div className={styles.columnRightText}>
            <h1 className={styles.secondFont}>Season Finale Euphoria</h1>
            <p className={styles.firstFont}>
              We watched the season finale of Euphoria so you don't have to.
              Here's everything we learned that you need to know.
            </p>
          </div>
        </div>
      </main>
    </>
  );
}

// <div className={styles.containerTest}>
//   <div className={styles.imagetest}>
//     <img src="/dancing.png" alt="kids dancing" width={711} height={367} />
//   </div>
//   <div className={styles.text}>
//     <h1 className={styles.fourthFont}>Dancing Across America</h1>
//     <p className={styles.thirdFont}>
//       Kids all over the country are dancing at the prom. We heard their
//       stories. Who will you take?
//     </p>
//   </div>
// </div>;

// <div className={styles.containerTest2}>
//   <div className={styles.imagetest2}>
//     <Image
//       src="/dancing.png"
//       alt="kids dancing"
//       width={711}
//       height={367}
//     />
//   </div>
//   <div className={styles.text}>
//     <h1 className={styles.fourthFont}>Dancing Across America</h1>
//     <p className={styles.thirdFont}>
//       Kids all over the country are dancing at the prom. We heard
//       their stories. Who will you take?
//     </p>
//   </div>
// </div>;

//  <div className={styles.grid}>
//    <a
//      href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//      className={styles.card}
//      target="_blank"
//      rel="noopener noreferrer"
//    >
//      <h2 className={inter.className}>
//        Docs <span>-&gt;</span>
//      </h2>
//      <p className={inter.className}>
//        Find in-depth information about Next.js features and&nbsp;API.
//      </p>
//    </a>

//    <a
//      href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//      className={styles.card}
//      target="_blank"
//      rel="noopener noreferrer"
//    >
//      <h2 className={inter.className}>
//        Learn <span>-&gt;</span>
//      </h2>
//      <p className={inter.className}>
//        Learn about Next.js in an interactive course with&nbsp;quizzes!
//      </p>
//    </a>

//    <a
//      href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//      className={styles.card}
//      target="_blank"
//      rel="noopener noreferrer"
//    >
//      <h2 className={inter.className}>
//        Templates <span>-&gt;</span>
//      </h2>
//      <p className={inter.className}>
//        Discover and deploy boilerplate example Next.js&nbsp;projects.
//      </p>
//    </a>

//    <a
//      href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//      className={styles.card}
//      target="_blank"
//      rel="noopener noreferrer"
//    >
//      <h2 className={inter.className}>
//        Deploy <span>-&gt;</span>
//      </h2>
//      <p className={inter.className}>
//        Instantly deploy your Next.js site to a shareable URL
//        with&nbsp;Vercel.
//      </p>
//    </a>
//  </div>;
